#

import os
import sys
sys.path.append(os.path.join(os.getcwd(), os.pardir, os.pardir, 'scripts'))
import myShutil # for better copytree()

# we need to specify an absolute path so this SConstruct file
# can be called from any other SConstruct file
cwd = os.getcwd() 


dest = os.path.join(cwd,os.pardir,os.pardir,os.pardir,'vnmr','templates')
if not os.path.exists(dest) :
    os.makedirs(dest)
myShutil.copytree('layout',os.path.join(dest,'layout'),symlinks = False)
